#
# example  for coffeedripper and barista
#
guard 'coffeedripper'  do
  watch(%r{^app/coffeescripts/(.+)\.bean$}) {|m| "#{m[1]}.bean"}
end
#
# example for coffeedripper and rails3.1
#
guard 'coffeedripper', :output => 'app/assets/javascripts/' do
  watch(%r{^app/assets/javascripts/(.+)\.bean$}) {|m| "#{m[1]}.bean"}
end
